services:
  mysql_db:
    image: mysql:8.0
    restart: always
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: dbname
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - yii

  nginx:
    container_name: yii_nginx
    image: nginx:latest
    ports:
      - 5000:80
    volumes:
      - ./www:/var/www
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - yii
    links:
      - php

  php:
    container_name: yii_php
    extends:
      file: base-php/base-php.yml
      service: base-php
    restart: always
    volumes:
      - ./www:/var/www
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    links:
      - mysql_db
    networks:
      - yii

networks:
  yii:

volumes:
  db: